# Checksum copied from "s5cmd_checksums.txt" associated with the s5cmd GitHub release

# The section below is auto-generated by scripts/update_s5cmdUrls.cmake.py
# Do not edit this section directly.

set(version "2.3.0")

set(linux32_filename      "s5cmd_${version}_Linux-32bit.tar.gz")
set(linux32_sha256        "33e73005f183e5758161b32440ec65b15c934eb60c3b42795fb335418ca110ac")

set(linux64_filename      "s5cmd_${version}_Linux-64bit.tar.gz")
set(linux64_sha256        "de0fdbfa3aceae55e069ba81a0fc17b2026567637603734a387b2fca06c299b4")

set(linuxarm64_filename   "s5cmd_${version}_Linux-arm64.tar.gz")
set(linuxarm64_sha256     "1439f0d00ecedcd2a2f1f2c6749bbb0152b2257bf5086f29646ec8ae38798e24")

set(linuxppc64le_filename "s5cmd_${version}_Linux-ppc64le.tar.gz")
set(linuxppc64le_sha256   "cb9f6926f94787f635f0a9de9242fca24b1461befd9a14b8a1084b04f76dbb45")

set(macos64_filename      "s5cmd_${version}_macOS-64bit.tar.gz")
set(macos64_sha256        "df6f76f6d317c4d051ad083219ed36eb8d8e5ebc55ceeeb91f5e66cdc3ac71fb")

set(macosarm64_filename   "s5cmd_${version}_macOS-arm64.tar.gz")
set(macosarm64_sha256     "ae007bc96276f498ae3c1fb017e57630cf93ef260cfe7e97b365522e240c973f")

set(win32_filename        "s5cmd_${version}_Windows-32bit.zip")
set(win32_sha256          "a5ff4e82f679dbd45310a0d57519fcfe66c1df2703d883ff9f40a20db7e65fe8")

set(win64_filename        "s5cmd_${version}_Windows-64bit.zip")
set(win64_sha256          "9d8a98c1d9f6284c6d54aeec3daeb5f1412fd101850ae756c1e70dd8ffe52166")

set(winarm64_filename     "s5cmd_${version}_Windows-arm64.zip")
set(winarm64_sha256       "0d99ce0cbf4a266e7fd9b3cd2682384fb7b432754eb52f17f9a9f7cbe6bcca55")

# The section above is auto-generated by scripts/update_s5cmdUrls.cmake.py
# Do not edit this section directly.

cmake_host_system_information(RESULT is_64bit QUERY IS_64BIT)

set(archive "linux32")
if(is_64bit)
  set(archive "linux64")
  if(${CMAKE_SYSTEM_PROCESSOR} STREQUAL "aarch64")
    set(archive "linuxarm64")
  elseif(${CMAKE_SYSTEM_PROCESSOR} STREQUAL "ppc64le")
    set(archive "linuxppc64le")
  endif()
endif()

if(APPLE)
  set(archive "macos64")
  if(${CMAKE_SYSTEM_PROCESSOR} STREQUAL "arm64")
    set(archive "macosarm64")
  endif()
endif()

if(WIN32)
  set(archive "win32")
  if(is_64bit)
    set(archive "win64")
    if(${CMAKE_SYSTEM_PROCESSOR} STREQUAL "ARM64" OR "$ENV{SETUPTOOLS_EXT_SUFFIX}" MATCHES arm64)
      set(archive "winarm64")
    endif()
  endif()
endif()

if(NOT DEFINED "${archive}_filename")
  message(FATAL_ERROR "Failed to determine which archive to download: '${archive}_filename' variable is not defined")
endif()

if(NOT DEFINED "${archive}_sha256")
  message(FATAL_ERROR "Could you make sure variable '${archive}_sha256' is defined ?")
endif()

set(s5cmd_archive_filename "${${archive}_filename}")
set(s5cmd_archive_sha256 "${${archive}_sha256}")

set(s5cmd_archive_url "https://github.com/peak/s5cmd/releases/download/v${version}/${s5cmd_archive_filename}")
