name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  FORCE_COLOR: 3

jobs:
  pre-commit:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: --hook-stage manual --all-files
      - name: Run PyLint
        run: |
          echo "::add-matcher::$GITHUB_WORKSPACE/.github/matchers/pylint.json"
          pipx run nox -s pylint

  checks:
    name: Check Python ${{ matrix.python-version }} on ${{ matrix.runs-on }}
    runs-on: ${{ matrix.runs-on }}
    needs: [pre-commit]
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.12"]
        runs-on: [ubuntu-latest, macos-latest, windows-latest]

        include:
          - python-version: pypy-3.10
            runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true

      - name: Install package
        run: python -m pip install .[test]

      - name: Test package
        run: >-
          python -m pytest -ra --cov --cov-report=xml --cov-report=term
          --durations=20

  checks-cibw:
    name: >
      Check Python ${{ matrix.python-version }} on ${{ matrix.runs-on }} (${{
      matrix.arch }})
    runs-on: ${{ matrix.runs-on }}
    needs: [pre-commit]
    strategy:
      fail-fast: false
      matrix:
        include:
          - runs-on: macos-14
            python-version: cp312
            arch: "arm64"
            use_qemu: false

          - runs-on: windows-latest
            python-version: cp312
            arch: "ARM64"
            test-skip: "*-win_arm64"
            use_qemu: false

          - runs-on: ubuntu-latest
            python-version: cp312
            arch: "aarch64"
            use_qemu: true

          - runs-on: ubuntu-latest
            python-version: cp312
            arch: "ppc64le"
            use_qemu: true
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.0.0
        if: matrix.use_qemu

      - uses: pypa/cibuildwheel@v2.18.0
        env:
          CIBW_BUILD: "${{ matrix.python-version }}-*"
          CIBW_ARCHS: "${{ matrix.arch }}"
          CIBW_TEST_SKIP: "${{ matrix.test-skip }}"
